#!/usr/bin/env python
from prenestr.server import Prenestr
from prenestr.daemon import Daemon
import sys

class PrenestrDaemon(Daemon):

    def run(self):
        Prenestr()

def init():
    daemon = PrenestrDaemon("/tmp/prenestr.pid")
    if len(sys.argv) == 2:
        if 'start' == sys.argv[1]:
            daemon.start()
        elif 'stop' == sys.argv[1]:
            daemon.stop()
        elif 'restart' == sys.argv[1]:
            daemon.restart()
        else:
            print "Unknown command"
            sys.exit(2)
        sys.exit(0)
    else:
        print "usage: %s start|stop|restart" % sys.argv[0]
        sys.exit(2)


if __name__ == '__main__':
    init()
